export enum EOrderStatus {
  SAVED = 'SAVED',
  CONFIRMED = 'CONFIRMED',
  FIRST_PAYMENT_RECEIVED = 'FIRST_PAYMENT_RECEIVED',
  WAITING_FOR_DESIGN = 'WAITING_FOR_DESIGN',
  IN_PRODUCTION = 'IN_PRODUCTION',
  PRODUCTION_COMPLETED = 'PRODUCTION_COMPLETED',
  READY_TO_DELIVER = 'READY_TO_DELIVER',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  DESIGN_COMPLETED = 'DESIGN_COMPLETED',
}
